"""empty message

Revision ID: 272156c5a6c7
Revises: 2c3af3cac3f3
Create Date: 2020-06-08 18:52:15.930331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272156c5a6c7'
down_revision = '2c3af3cac3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.drop_column('roles', 'permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permission', sa.INTEGER(), nullable=True))
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###
