"""empty message

Revision ID: b31ace9d331b
Revises: ecd80f47a820
Create Date: 2020-06-09 16:24:51.026638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31ace9d331b'
down_revision = 'ecd80f47a820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'permission')
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    op.add_column('roles', sa.Column('permission', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
